---
- name: Sunucu Zırhlama Operasyonu
  hosts: "{{ target_hosts | default('hardening_targets') }}" # Target specific hosts, default to 'hardening_targets'
  become: true # Execute commands with sudo
  
  roles:
    - server_hardening # Use the hardening role defined earlier
